[package]
name = "tinygif"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-graphics = "0.8.0"
heapless = "0.7.16"


[dev-dependencies]
nu-pretty-hex = "0.80.0"
bmp = "0.5.0"
